[build]
publish = "public"
command = "hugo --cleanDestinationDir --forceSyncStatic --gc --ignoreCache --minify"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200
